### ISSUE TITLE
Need help with configuration

### ISSUE THREAD

**Issue by Qintiy** [privacyidea/privacyidea-pam#14]
I am trying to connect PrivacyIdea and OpenVPN with this privacyidea-pam method and have no success in implementing it. I used this code and modified
`auth    [success=1 default=ignore]      /lib64/security/privacyidea-pam.so
url=https://server_ip
auth    requisite           pam_deny.so
auth    required            pam_permit.so
session sufficient          pam_permit.so
account sufficient          pam_permit.so`

and when I use tcpdumb on privacyidea there is no traffic when trying to login in openvpn

**Comment by nilsbehlen** [comment]
So you do not get prompted for an OTP?
In that case you need to check your setup.

**Comment by nilsbehlen** [comment]
If your config is correct, you would get prompted for an OTP, regardless of whether you have a token in privacyidea or not.
There will also be no connection prior to that prompt for OTP (unless you use sendPass options), so you can check if the module loads correctly if you get prompted.

I am not an expert for PAM configurations or Linux in general, so i can not really assist you there. I just noticed in the second you wrote `privacyidea-pam` with a hyphen but it should be with `_` like in the first which looks correct. However, i do not know if the path is required if that path is the default search path anyway, so you could try just `pam_privacyidea.so` like in the samples:
https://github.com/privacyidea/privacyidea-pam/blob/main/samples/privacyidea-auth

**Comment by nilsbehlen** [comment]
Yes you need to link with curl (`-lcurl`), but i also do not want to help everyone build this thing. This is the third or forth issue of this kind, so if you are unable to build it, you can just use the pre-built one provided in the release section:
https://github.com/privacyidea/privacyidea-pam/releases/tag/v1.0.0

**Comment by nilsbehlen** [comment]
its an L for link in `-lcurl`

**Comment by nilsbehlen** [comment]
then you need to check for the symbols with `ldd` or something like that.
This is not the place for these kind of problems. I am not going to help you with that because that is not my job.
If this module does not work or behaves wrong, this is would be the place to discuss that.
Im sorry but like i said this is the 3rd or 4th time and it is getting exhausting to answer these questions.

**Comment by nilsbehlen** [comment]
Yes, it is an issue with your setup. That is why it is exhausting to answer these questions. You should be able to search for solutions yourself and if you can clearly identify a problem with this project, you can make an issue about it.

**Comment by plettich** [comment]
actually i can confirm this behaviour on a Ubuntu 20.04 machine. We probably need to switch the order of the `$(LDFLAGS)` in the Makefile. I'll make a PR.

**Comment by nilsbehlen** [comment]
does that fix his problem?

**Comment by plettich** [comment]
> does that fix his problem?

It fixed it in my setup where i had the same undefined symbols
