### ISSUE TITLE
Call pam_get_authtok only if option config.sendUnixPass is set

### ISSUE THREAD

**Issue by ahaupt** [privacyidea/privacyidea-pam#2]
I wonder if a call to ```pam_get_authtok``` in https://github.com/privacyidea/privacyidea-pam/blob/d70204eda0119479f4eb485453e1f71cce74912e/src/pam_privacyidea.cpp#L164 should be done only if config.sendUnixPass is set.

In case the first factor is e.g. a public key, calling pam_get_authtok results in asking for a password although this might not be desired.

I can provide a PR (if my assumption is correct ;-))

**Comment by nilsbehlen** [comment]
You are right, it was an oversight and has been fixed in 5d07a06.
