### ISSUE TITLE
undefined symbol: curl_easy_perform

### ISSUE THREAD

**Issue by gpappsoft** [privacyidea/privacyidea-pam#5]
Installed dependencies and compiled the module as described. Module will fail with error:

`PAM unable to dlopen(pam_privacyidea.so): /lib/security/pam_privacyidea.so: undefined symbol: curl_easy_perform`

Pam stack configuration:
`auth required pam_privacyidea.so url=https://localhost nossl debug`

System: Debian 11.7 

Linked libs (`ldd pam_privacyidea.so `):
	linux-vdso.so.1 (0x00007ffd269e6000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa73c3f2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa73c3d8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa73c204000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa73c0c0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa73c6aa000)

**Comment by nilsbehlen** [comment]
you have to link with libcurl (`libcurl4-openssl-dev`) aswell, the flag is `-lcurl`

**Comment by tgrymatt** [comment]
I have the same problem. But for me it looks like, that it is linked?

 libcurl4-openssl-dev is installed:

ii  libcurl4-openssl-dev:amd64                 7.81.0-1ubuntu1.13                         amd64        development files and documentation for libcurl (OpenSSL flavour)


root@tgm-test-01:/opt/pam-otp/privacyidea-pam-0.9.0# make
g++ -c -g -Wall -fPIC -Iinclude src/pam_privacyidea.cpp -o src/pam_privacyidea.o
g++ -c -g -Wall -fPIC -Iinclude src/PrivacyIDEA.cpp -o src/PrivacyIDEA.o
g++ -Wno-undef -lcurl --shared -o pam_privacyidea.so src/pam_privacyidea.o src/PrivacyIDEA.o

root@tgm-test-01:/opt/pam-otp/privacyidea-pam-0.9.0# make install
strip --strip-unneeded pam_privacyidea.so
cp pam_privacyidea.so /lib64/security

Config in /etc/pam.d/sshd after "@include common-auth"

auth    required                        /lib64/security/pam_privacyidea.so url=https://otp.MYDOMAIN realm=otp.MYDOMAIN debug nossl [prompt=Please enter your OneTimePassword]

And if I try to login via SSH journalctl shows:

Sep 09 15:38:15 tgm-test-01 sshd[25166]: PAM unable to dlopen(/lib64/security/pam_privacyidea.so): /lib64/security/pam_privacyidea.so: undefined symbol: curl_easy_perform
Sep 09 15:38:15 tgm-test-01 sshd[25166]: PAM adding faulty module: /lib64/security/pam_privacyidea.so

**Comment by nilsbehlen** [comment]
Does it work if you use the commands to build manually?
```
g++ -c -g -Wall -fPIC -Iinclude src/pam_privacyidea.cpp -o src/pam_privacyidea.o
g++ -c -g -Wall -fPIC -Iinclude src/PrivacyIDEA.cpp -o src/PrivacyIDEA.o
g++ -Wno-undef -lcurl --shared -o pam_privacyidea.so src/pam_privacyidea.o src/PrivacyIDEA.o
```

**Comment by nilsbehlen** [comment]
i suppose you use ubuntu?
