### ISSUE TITLE
ERR904: The user can not be found in any resolver in this realm! (Code: 904)

### ISSUE THREAD

**Issue by tgrymatt** [privacyidea/privacyidea-pam#7]
On older machines I use the python_pam module which works absolutely fine with my user and the realm MY-OTP-REALM.

Now I am trying to use this plugin on a Linux Mint 21.2 machine:
I downloaded the release v.0.9.0 and copied the pam_privacyidea.so file into /lib/security
In /etc/pam.d/sshd I configured:

@include common-auth
auth    required                        /lib/security/pam_privacyidea.so url=https://otp.MY-DOMAIN realm=MY-OTP-REALM debug nossl [prompt=Please enter your OneTimePassword]

Now I try to login and then I can found in journalctl:

Sep 09 15:12:04 SERVERNAME pam_privacyidea[22681]: pam_privacyidea(sshd:auth): Offline retval: 5
Sep 09 15:12:04 SERVERNAME pam_privacyidea[22681]: pam_privacyidea(sshd:auth): Sending pass=729761&user=tgm to https://otp.MYDOMAIN/validate/check
Sep 09 15:12:05 SERVERNAME pam_privacyidea[22681]: pam_privacyidea(sshd:auth): {"detail": null, "id": 1, "jsonrpc": "2.0", "result": {"error": {"code": 904, "message": "ERR904: The user can not be found in any resolver in this realm!"}, "status": false}, "time": 1694265125.1187627, "version": "privacyIDEA 3.8", "signature": "rsa_sha256_pss:2ded8692ab676cbd05b6b39ae541941002b4676bdda38c5931b2410029ed327dea496284344f53746e856463e9588e9b49d3aa7d70aa68b5604b18eabea3c6a415c4ba3ab7dcc2b503eac0bcf5140d97390c0ade5fc1be7c2aad02952e1fe142bc0f3735bc57fd8db9425464be78ef9fcedfaa31b00508fc242a7cfcc342e1822cb06ca9cce3ed699a06721b535ee22f8d692aab42fde4e7288ecc7682f224dbeb3b181a074f5a1eeaa4a2450404cb34a858be5b5fa607796bceca9e243bc183416da6e8dcf2a1244e80d9e273c0a319d6d8719bfac58dade49530af94754080fbe91ae5e4f64439301a935bc16d8adcba7e2d2693a6ef7a40f076102266e913"}
Sep 09 15:12:05 SERVERNAME pam_privacyidea[22681]: pam_privacyidea(sshd:auth): Unable to authenticate with privacyIDEA: ERR904: The user can not be found in any resolver in this realm! (Code: 904)
Sep 09 15:12:07 SERVERNAME sshd[22679]: error: PAM: Authentication failure for tgm from 10.19.6.212

Interesting is, that I can see in TCPDUMP that the client and the PrivacyIdea server are exchanging data. But on privacy idea I can see nothing about this in the audit log.  And at apache log file of privacy idea I can see, that there is an request:

192.168.16.121 - - [09/Sep/2023:15:23:25 +0200] 400 "POST /validate/check HTTP/1.1"  777 "-" "PAM/1.0.0"

Any hints? Thanks and kind regards

Tobias

**Comment by nilsbehlen** [comment]
Hi,
it seems the realm is not sent at all, therefore it is not properly read from the config. I will look into it, there seems to be a similar problem with sendPassword
